nodes:
- input.visual:
    source: 0
- model.yolo
- model.posenet
- custom_nodes.dabble.posture_check
- draw.poses
- output.screen
- output.csv_writer:
    stats_to_track: ["Tick", "Tock", "Head Angle High", "Head Angle Low", "Neck Angle Forward", "Neck Angle Backward", "Back Angle Forward", "Back Angle Backward"]
    file_path: "log/posture_record.csv"
    logging_interval: 10